server:
  port: 9000
spring:
  application:
    name: clouddemo-config-client
#eureka:
  #instance:
    #hostname: micro.service.user
    #prefer-ip-address: true
  #client:
    #fetch-registry: true
    #register-with-eureka: true
info:
  application:
    name: ${spring.application.name}
    port: ${server.port}