server:
  port: 9000
spring:
  application:
    name: clouddemo-config-client
eureka:
 client:
  service-url:
   defaultZone: http://eureka-test.com:7001/eureka/
info:
  application:
    name: ${spring.application.name}
    port: ${server.port}