server:
  port: 9001
spring:
  application:
    name: clouddemo-config-client-dev
eureka:
 client:
  service-url:
   defaultZone: http://eureka-dev.com:7001/eureka/
info:
  application:
    name: ${spring.application.name}
    port: ${server.port}